apiVersion: v1
kind: Service
metadata:
  name: moviereview-service
spec:
  selector:
    app: moviereview
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
